export interface Product {
  id: string
  name: string
  description: string
  shortDescription: string
  price: string
  category: string
  image: string
  features: string[]
}

export const products: Product[] = [
  // MDF Beds
  {
    id: "mdf-bed-1",
    name: "Classic MDF King Bed",
    description: "A refined king-size bed built from high-density MDF with a smooth, durable laminate finish. The bold headboard design adds a classic touch while maintaining a clean, modern silhouette suited for contemporary Kenyan bedrooms.",
    shortDescription: "Classic king-size MDF bed with bold headboard",
    price: "KES 175,000",
    category: "MDF Beds",
    image: "/mdfs/mdf-bed-1.jpeg",
    features: ["High-Density MDF", "King Size", "Laminate Finish", "Classic Headboard"],
  },
  {
    id: "mdf-bed-2",
    name: "Classic MDF King Bed",
    description: "A refined king-size bed built from high-density MDF with a smooth, durable laminate finish. The bold headboard design adds a classic touch while maintaining a clean, modern silhouette suited for contemporary Kenyan bedrooms.",
    shortDescription: "Classic king-size MDF bed with bold headboard",
    price: "KES 175,000",
    category: "MDF Beds",
    image: "/mdfs/mdf-bed-2.jpeg",
    features: ["High-Density MDF", "King Size", "Laminate Finish", "Classic Headboard"],
  },
  {
    id: "mdf-bed-3",
    name: "Classic MDF King Bed",
    description: "A refined king-size bed built from high-density MDF with a smooth, durable laminate finish. The bold headboard design adds a classic touch while maintaining a clean, modern silhouette suited for contemporary Kenyan bedrooms.",
    shortDescription: "Classic king-size MDF bed with bold headboard",
    price: "KES 175,000",
    category: "MDF Beds",
    image: "/mdfs/mdf-bed-3.jpeg",
    features: ["High-Density MDF", "King Size", "Laminate Finish", "Classic Headboard"],
  },
  {
    id: "mdf-bed-4",
    name: "Classic MDF King Bed",
    description: "A refined king-size bed built from high-density MDF with a smooth, durable laminate finish. The bold headboard design adds a classic touch while maintaining a clean, modern silhouette suited for contemporary Kenyan bedrooms.",
    shortDescription: "Classic king-size MDF bed with bold headboard",
    price: "KES 175,000",
    category: "MDF Beds",
    image: "/mdfs/mdf-bed-4.jpeg",
    features: ["High-Density MDF", "King Size", "Laminate Finish", "Classic Headboard"],
  },
  {
    id: "mdf-bed-5",
    name: "Classic MDF King Bed",
    description: "A refined king-size bed built from high-density MDF with a smooth, durable laminate finish. The bold headboard design adds a classic touch while maintaining a clean, modern silhouette suited for contemporary Kenyan bedrooms.",
    shortDescription: "Classic king-size MDF bed with bold headboard",
    price: "KES 175,000",
    category: "MDF Beds",
    image: "/mdfs/mdf-bed-5.jpeg",
    features: ["High-Density MDF", "King Size", "Laminate Finish", "Classic Headboard"],
  },
  {
    id: "mdf-bed-6",
    name: "Classic MDF King Bed",
    description: "A refined king-size bed built from high-density MDF with a smooth, durable laminate finish. The bold headboard design adds a classic touch while maintaining a clean, modern silhouette suited for contemporary Kenyan bedrooms.",
    shortDescription: "Classic king-size MDF bed with bold headboard",
    price: "KES 175,000",
    category: "MDF Beds",
    image: "/mdfs/mdf-bed-6.jpeg",
    features: ["High-Density MDF", "King Size", "Laminate Finish", "Classic Headboard"],
  },
  // Dining Tables
  {
    id: "dining-table-1",
    name: "Dining Table",
    description: "A spacious 6-seater dining table built for family gatherings and everyday meals. Crafted with a sturdy engineered wood base and a smooth, easy-clean tabletop surface. The clean lines and neutral finish complement a wide range of interior styles, from modern to transitional.",
    shortDescription: "Spacious 6-seater dining table with a clean modern finish",
    price: "KES 85,000",
    category: "Dining",
    image: "/dinings/dining-table-1.jpeg",
    features: ["Seats 6 People", "Engineered Wood Base", "Easy-Clean Surface", "Modern Design"],
  },
  {
    id: "dining-table-2",
    name: "Dining Table",
    description: "A spacious 6-seater dining table built for family gatherings and everyday meals. Crafted with a sturdy engineered wood base and a smooth, easy-clean tabletop surface. The clean lines and neutral finish complement a wide range of interior styles, from modern to transitional.",
    shortDescription: "Spacious 6-seater dining table with a clean modern finish",
    price: "KES 85,000",
    category: "Dining",
    image: "/dinings/dining-table-2.jpeg",
    features: ["Seats 6 People", "Engineered Wood Base", "Easy-Clean Surface", "Modern Design"],
  },
  {
    id: "dining-table-4",
    name: "Dining Table",
    description: "A spacious 6-seater dining table built for family gatherings and everyday meals. Crafted with a sturdy engineered wood base and a smooth, easy-clean tabletop surface. The clean lines and neutral finish complement a wide range of interior styles, from modern to transitional.",
    shortDescription: "Spacious 6-seater dining table with a clean modern finish",
    price: "KES 85,000",
    category: "Dining",
    image: "/dinings/dining-table-4.jpeg",
    features: ["Seats 6 People", "Engineered Wood Base", "Easy-Clean Surface", "Modern Design"],
  },
  {
    id: "dining-table-5",
    name: "Dining Table",
    description: "A spacious 6-seater dining table built for family gatherings and everyday meals. Crafted with a sturdy engineered wood base and a smooth, easy-clean tabletop surface. The clean lines and neutral finish complement a wide range of interior styles, from modern to transitional.",
    shortDescription: "Spacious 6-seater dining table with a clean modern finish",
    price: "KES 85,000",
    category: "Dining",
    image: "/dinings/dining-table-5.jpeg",
    features: ["Seats 6 People", "Engineered Wood Base", "Easy-Clean Surface", "Modern Design"],
  },
  // Coffee Courts
  {
    id: "modern-oak-bed-queen",
    name: "Coffee Court",
    description: "A stylish coffee court unit designed to display and store your beverage essentials in one sleek piece. Features open shelving for cups and décor, with enclosed lower compartments for bottles and accessories.",
    shortDescription: "Stylish coffee bar unit with open and closed storage",
    price: "KES 35,000",
    category: "Coffee Courts",
    image: "/coffee-courts/coffee-court-1.jpg",
    features: ["Open Shelving", "Enclosed Storage", "MDF Construction", "Modern Finish"],
  },
  // Console Tables
  {
    id: "console-table-1",
    name: "Console Table",
    description: "A sleek and versatile console table perfect for entryways, hallways, or behind sofas. Features a slim profile with a smooth laminate finish and sturdy MDF construction.",
    shortDescription: "Slim entryway console table with smooth finish",
    price: "KES 40,000",
    category: "Console Tables",
    image: "/console-tables/console-table-1.jpeg",
    features: ["Slim Profile", "MDF Construction", "Laminate Finish", "Versatile Placement"],
  },
  {
    id: "console-table-2",
    name: "Console Table",
    description: "A sleek and versatile console table perfect for entryways, hallways, or behind sofas. Features a slim profile with a smooth laminate finish and sturdy MDF construction.",
    shortDescription: "Slim entryway console table with smooth finish",
    price: "KES 40,000",
    category: "Console Tables",
    image: "/console-tables/console-table-2.jpeg",
    features: ["Slim Profile", "MDF Construction", "Laminate Finish", "Versatile Placement"],
  },
  {
    id: "console-table-3",
    name: "Console Table",
    description: "A sleek and versatile console table perfect for entryways, hallways, or behind sofas. Features a slim profile with a smooth laminate finish and sturdy MDF construction.",
    shortDescription: "Slim entryway console table with smooth finish",
    price: "KES 40,000",
    category: "Console Tables",
    image: "/console-tables/console-table-3.jpeg",
    features: ["Slim Profile", "MDF Construction", "Laminate Finish", "Versatile Placement"],
  },
  {
    id: "console-table-4",
    name: "Console Table",
    description: "A sleek and versatile console table perfect for entryways, hallways, or behind sofas. Features a slim profile with a smooth laminate finish and sturdy MDF construction.",
    shortDescription: "Slim entryway console table with smooth finish",
    price: "KES 40,000",
    category: "Console Tables",
    image: "/console-tables/console-table-4.jpeg",
    features: ["Slim Profile", "MDF Construction", "Laminate Finish", "Versatile Placement"],
  },
  // Side Tables
  {
    id: "entryway-console-table",
    name: "Elegant Side Table",
    description: "A sophisticated side table featuring a marble-effect top and a gold-finished metal frame. Compact enough to sit beside a sofa or armchair, yet striking enough to stand out as a decorative accent piece.",
    shortDescription: "Marble top side table with gold frame",
    price: "KES 13,000",
    category: "Side Tables",
    image: "/side-tables/side-table-1.jpg",
    features: ["Marble-Effect Top", "Gold Metal Frame", "Compact Size", "Accent Design"],
  },
  // Coffee Tables
  {
    id: "rustic-wood-console",
    name: "Beautiful Coffee Table",
    description: "A charming coffee table handcrafted from reclaimed wood with a natural distressed finish. Every piece carries its own unique grain and character, making it a one-of-a-kind centrepiece for your living room.",
    shortDescription: "Handcrafted reclaimed wood coffee table",
    price: "KES 10,000",
    category: "Coffee Tables",
    image: "/coffee-tables/coffee-table-1.jpg",
    features: ["Reclaimed Wood", "Natural Distressed Finish", "Handcrafted", "Unique Grain"],
  },
  // Mirrors
  {
    id: "mirro1-1",
    name: "Mirror",
    description: "A beautifully framed wall mirror that adds depth, light, and elegance to any room. The sturdy frame and clean reflective surface make it a versatile accent piece for bedrooms, living rooms, or entryways.",
    shortDescription: "Elegant framed wall mirror",
    price: "KES 15,000",
    category: "Mirrors",
    image: "/mirrors/mirror-1.jpeg",
    features: ["Framed Design", "Wall Mounted", "Bedroom & Living Use", "Elegant Finish"],
  },
  {
    id: "mirror-2",
    name: "Mirror",
    description: "A beautifully framed wall mirror that adds depth, light, and elegance to any room. The sturdy frame and clean reflective surface make it a versatile accent piece for bedrooms, living rooms, or entryways.",
    shortDescription: "Elegant framed wall mirror",
    price: "KES 15,000",
    category: "Mirrors",
    image: "/mirrors/mirror-2.jpeg",
    features: ["Framed Design", "Wall Mounted", "Bedroom & Living Use", "Elegant Finish"],
  },
]

export const categories = [
  "All",
  "Wooden Beds",
  "MDF Beds",
  "Console Tables",
  "Dining",
  "Coffee Tables",
  "Coffee Courts",
  "Side Tables",
  "Mirrors",
]
